;;;; chicken.compiler.chicken.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'chicken.compiler.chicken
      'chicken.compiler.chicken
      (scheme#list)
      '()
      (scheme#list)
      (scheme#list))))

;; END OF FILE
